cd /D "%~dp0" || exit /b

IF "%CMAKE_BUILD_TYPE%"=="" set CMAKE_BUILD_TYPE=Release
set BUILD_DIR=VSBullet3Build
mkdir %BUILD_DIR%
cd %BUILD_DIR% || exit /b
cmake ../bullet3 ^
    %CMAKE_OPTIONS% ^
    -DBUILD_BULLET2_DEMOS=OFF ^
    -DBUILD_BULLET_ROBOTICS_EXTRA=OFF ^
    -DBUILD_BULLET_ROBOTICS_GUI_EXTRA=OFF ^
    -DBUILD_CLSOCKET=OFF ^
    -DBUILD_CONVEX_DECOMPOSITION_EXTRA=OFF ^
    -DBUILD_CPU_DEMOS=OFF ^
    -DBUILD_ENET=OFF ^
    -DBUILD_EXTRAS=OFF ^
    -DBUILD_GIMPACTUTILS_EXTRA=OFF ^
    -DBUILD_HACD_EXTRA=OFF ^
    -DBUILD_INVERSE_DYNAMIC_EXTRA=OFF ^
    -DBUILD_OBJ2SDF_EXTRA=OFF ^
    -DBUILD_OPENGL3_DEMOS=OFF ^
    -DBUILD_PYBULLET=OFF ^
    -DBUILD_SERIALIZE_EXTRA=OFF ^
    -DBUILD_SHARED_LIBS=OFF ^
    -DBUILD_UNIT_TESTS=OFF ^
    -DUSE_DOUBLE_PRECISION=ON ^
    -DUSE_GLUT=OFF ^
    -DUSE_GRAPHICAL_BENCHMARK=OFF || exit /b
cmake ^
    --build . ^
    --config %CMAKE_BUILD_TYPE% ^
    --verbose || exit /b
