#include <Mlib/Misc/Pragma_Clang.hpp>
#define MINIMP3_IMPLEMENTATION
PRAGMA_CLANG_DIAGNOSTIC_PUSH
PRAGMA_CLANG_DIAGNOSTIC_IGNORED(-Wsign-conversion)
PRAGMA_CLANG_DIAGNOSTIC_IGNORED(-Wimplicit-int-float-conversion)
PRAGMA_CLANG_DIAGNOSTIC_IGNORED(-Wshorten-64-to-32)
#include "minimp3_ex.h"
PRAGMA_CLANG_DIAGNOSTIC_POP
